package entities;
// Generated Jul 13, 2016 9:48:43 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommentId generated by hbm2java
 */
@Embeddable
public class CommentId implements java.io.Serializable {

	private int idComment;
	private int userIdUser;
	private int taskIdTask;

	public CommentId() {
	}

	public CommentId(int idComment, int userIdUser, int taskIdTask) {
		this.idComment = idComment;
		this.userIdUser = userIdUser;
		this.taskIdTask = taskIdTask;
	}

	@Column(name = "idComment", nullable = false)
	public int getIdComment() {
		return this.idComment;
	}

	public void setIdComment(int idComment) {
		this.idComment = idComment;
	}

	@Column(name = "User_idUser", nullable = false)
	public int getUserIdUser() {
		return this.userIdUser;
	}

	public void setUserIdUser(int userIdUser) {
		this.userIdUser = userIdUser;
	}

	@Column(name = "Task_idTask", nullable = false)
	public int getTaskIdTask() {
		return this.taskIdTask;
	}

	public void setTaskIdTask(int taskIdTask) {
		this.taskIdTask = taskIdTask;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommentId))
			return false;
		CommentId castOther = (CommentId) other;

		return (this.getIdComment() == castOther.getIdComment()) && (this.getUserIdUser() == castOther.getUserIdUser())
				&& (this.getTaskIdTask() == castOther.getTaskIdTask());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdComment();
		result = 37 * result + this.getUserIdUser();
		result = 37 * result + this.getTaskIdTask();
		return result;
	}

}
