package entities;
// Generated Jul 13, 2016 9:48:43 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "taskmanager_db")
public class Comment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private CommentId id;
	private Task task;
	private User user;
	private String date;
	private String commentContent;

	public Comment() {
	}

	public Comment(CommentId id, Task task, User user) {
		this.id = id;
		this.task = task;
		this.user = user;
	}

	public Comment(CommentId id, Task task, User user, String date, String commentContent) {
		this.id = id;
		this.task = task;
		this.user = user;
		this.date = date;
		this.commentContent = commentContent;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idComment", column = @Column(name = "idComment", nullable = false)),
			@AttributeOverride(name = "userIdUser", column = @Column(name = "User_idUser", nullable = false)),
			@AttributeOverride(name = "taskIdTask", column = @Column(name = "Task_idTask", nullable = false)) })
	public CommentId getId() {
		return this.id;
	}

	public void setId(CommentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Task_idTask", nullable = false, insertable = false, updatable = false)
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_idUser", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "Date", length = 100)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "CommentContent", length = 100)
	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

}
