package entities;
// Generated Jul 13, 2016 9:48:43 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Priority generated by hbm2java
 */
@Entity
@Table(name = "priority", catalog = "taskmanager_db")
public class Priority implements java.io.Serializable {

	private int idPriority;
	private String priorityTipe;
	private Set<Task> tasks = new HashSet<Task>(0);

	public Priority() {
	}

	public Priority(int idPriority) {
		this.idPriority = idPriority;
	}

	public Priority(int idPriority, String priorityTipe, Set<Task> tasks) {
		this.idPriority = idPriority;
		this.priorityTipe = priorityTipe;
		this.tasks = tasks;
	}

	@Id

	@Column(name = "idPriority", unique = true, nullable = false)
	public int getIdPriority() {
		return this.idPriority;
	}

	public void setIdPriority(int idPriority) {
		this.idPriority = idPriority;
	}

	@Column(name = "PriorityTipe", length = 100)
	public String getPriorityTipe() {
		return this.priorityTipe;
	}

	public void setPriorityTipe(String priorityTipe) {
		this.priorityTipe = priorityTipe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "priority")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

}
