package entities;
// Generated Jul 13, 2016 9:48:43 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "taskmanager_db")
public class Project implements java.io.Serializable {

	private ProjectId id;
	private Release release;
	private User user;
	private String description;
	private String prjName;
	private Set<Task> tasks = new HashSet<Task>(0);

	public Project() {
	}

	public Project(ProjectId id, Release release, User user) {
		this.id = id;
		this.release = release;
		this.user = user;
	}

	public Project(ProjectId id, Release release, User user, String description, String prjName, Set<Task> tasks) {
		this.id = id;
		this.release = release;
		this.user = user;
		this.description = description;
		this.prjName = prjName;
		this.tasks = tasks;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idProject", column = @Column(name = "idProject", nullable = false)),
			@AttributeOverride(name = "userIdUser", column = @Column(name = "User_idUser", nullable = false)),
			@AttributeOverride(name = "userRoleIdRole", column = @Column(name = "User_Role_idRole", nullable = false)),
			@AttributeOverride(name = "releaseIdRelease", column = @Column(name = "Release_idRelease", nullable = false)) })
	public ProjectId getId() {
		return this.id;
	}

	public void setId(ProjectId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Release_idRelease", nullable = false, insertable = false, updatable = false)
	public Release getRelease() {
		return this.release;
	}

	public void setRelease(Release release) {
		this.release = release;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "User_idUser", referencedColumnName = "idUser", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "User_Role_idRole", referencedColumnName = "Role_idRole", nullable = false, insertable = false, updatable = false) })
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "Description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PrjName", length = 45)
	public String getPrjName() {
		return this.prjName;
	}

	public void setPrjName(String prjName) {
		this.prjName = prjName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

}
