package entities;
// Generated Jul 13, 2016 9:48:43 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Release generated by hbm2java
 */
@Entity
@Table(name = "release", catalog = "taskmanager_db")
public class Release implements java.io.Serializable {

	private int idRelease;
	private String version;
	private String date;
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<Task> tasks = new HashSet<Task>(0);

	public Release() {
	}

	public Release(int idRelease) {
		this.idRelease = idRelease;
	}

	public Release(int idRelease, String date, Set<Project> projects, Set<Task> tasks) {
		this.idRelease = idRelease;
		this.date = date;
		this.projects = projects;
		this.tasks = tasks;
	}

	@Id

	@Column(name = "idRelease", unique = true, nullable = false)
	public int getIdRelease() {
		return this.idRelease;
	}

	public void setIdRelease(int idRelease) {
		this.idRelease = idRelease;
	}

	@Version
	@Column(name = "Version", length = 100)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "Date", length = 100)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "release")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "release")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

}
