package entities;
// Generated Jul 13, 2016 9:48:43 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaskId generated by hbm2java
 */
@Embeddable
public class TaskId implements java.io.Serializable {

	private int idTask;
	private int projectIdProject;
	private int priorityIdPriority;
	private int statusIdStatus;
	private int releaseIdRelease;

	public TaskId() {
	}

	public TaskId(int idTask, int projectIdProject, int priorityIdPriority, int statusIdStatus, int releaseIdRelease) {
		this.idTask = idTask;
		this.projectIdProject = projectIdProject;
		this.priorityIdPriority = priorityIdPriority;
		this.statusIdStatus = statusIdStatus;
		this.releaseIdRelease = releaseIdRelease;
	}

	@Column(name = "idTask", nullable = false)
	public int getIdTask() {
		return this.idTask;
	}

	public void setIdTask(int idTask) {
		this.idTask = idTask;
	}

	@Column(name = "Project_idProject", nullable = false)
	public int getProjectIdProject() {
		return this.projectIdProject;
	}

	public void setProjectIdProject(int projectIdProject) {
		this.projectIdProject = projectIdProject;
	}

	@Column(name = "Priority_idPriority", nullable = false)
	public int getPriorityIdPriority() {
		return this.priorityIdPriority;
	}

	public void setPriorityIdPriority(int priorityIdPriority) {
		this.priorityIdPriority = priorityIdPriority;
	}

	@Column(name = "Status_idStatus", nullable = false)
	public int getStatusIdStatus() {
		return this.statusIdStatus;
	}

	public void setStatusIdStatus(int statusIdStatus) {
		this.statusIdStatus = statusIdStatus;
	}

	@Column(name = "Release_idRelease", nullable = false)
	public int getReleaseIdRelease() {
		return this.releaseIdRelease;
	}

	public void setReleaseIdRelease(int releaseIdRelease) {
		this.releaseIdRelease = releaseIdRelease;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaskId))
			return false;
		TaskId castOther = (TaskId) other;

		return (this.getIdTask() == castOther.getIdTask())
				&& (this.getProjectIdProject() == castOther.getProjectIdProject())
				&& (this.getPriorityIdPriority() == castOther.getPriorityIdPriority())
				&& (this.getStatusIdStatus() == castOther.getStatusIdStatus())
				&& (this.getReleaseIdRelease() == castOther.getReleaseIdRelease());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTask();
		result = 37 * result + this.getProjectIdProject();
		result = 37 * result + this.getPriorityIdPriority();
		result = 37 * result + this.getStatusIdStatus();
		result = 37 * result + this.getReleaseIdRelease();
		return result;
	}

}
