package entities;
// Generated Jul 13, 2016 9:48:43 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserId generated by hbm2java
 */
@Embeddable
public class UserId implements java.io.Serializable {

	private int idUser;
	private int roleIdRole;

	public UserId() {
	}

	public UserId(int idUser, int roleIdRole) {
		this.idUser = idUser;
		this.roleIdRole = roleIdRole;
	}

	@Column(name = "idUser", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "Role_idRole", nullable = false)
	public int getRoleIdRole() {
		return this.roleIdRole;
	}

	public void setRoleIdRole(int roleIdRole) {
		this.roleIdRole = roleIdRole;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserId))
			return false;
		UserId castOther = (UserId) other;

		return (this.getIdUser() == castOther.getIdUser()) && (this.getRoleIdRole() == castOther.getRoleIdRole());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUser();
		result = 37 * result + this.getRoleIdRole();
		return result;
	}

}
