package entities;
// Generated Jul 13, 2016 9:48:43 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserHasTaskId generated by hbm2java
 */
@Embeddable
public class UserHasTaskId implements java.io.Serializable {

	private int userIdUser;
	private int taskIdTask;
	private int statusIdStatus;

	public UserHasTaskId() {
	}

	public UserHasTaskId(int userIdUser, int taskIdTask, int statusIdStatus) {
		this.userIdUser = userIdUser;
		this.taskIdTask = taskIdTask;
		this.statusIdStatus = statusIdStatus;
	}

	@Column(name = "User_idUser", nullable = false)
	public int getUserIdUser() {
		return this.userIdUser;
	}

	public void setUserIdUser(int userIdUser) {
		this.userIdUser = userIdUser;
	}

	@Column(name = "Task_idTask", nullable = false)
	public int getTaskIdTask() {
		return this.taskIdTask;
	}

	public void setTaskIdTask(int taskIdTask) {
		this.taskIdTask = taskIdTask;
	}

	@Column(name = "Status_idStatus", nullable = false)
	public int getStatusIdStatus() {
		return this.statusIdStatus;
	}

	public void setStatusIdStatus(int statusIdStatus) {
		this.statusIdStatus = statusIdStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserHasTaskId))
			return false;
		UserHasTaskId castOther = (UserHasTaskId) other;

		return (this.getUserIdUser() == castOther.getUserIdUser())
				&& (this.getTaskIdTask() == castOther.getTaskIdTask())
				&& (this.getStatusIdStatus() == castOther.getStatusIdStatus());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserIdUser();
		result = 37 * result + this.getTaskIdTask();
		result = 37 * result + this.getStatusIdStatus();
		return result;
	}

}
