package entities;
// Generated Jul 13, 2016 9:48:43 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserHasTask generated by hbm2java
 */
@Entity
@Table(name = "user_has_task", catalog = "taskmanager_db")
public class UserHasTask implements java.io.Serializable {

	private UserHasTaskId id;
	private Status status;
	private Task task;
	private User user;

	public UserHasTask() {
	}

	public UserHasTask(UserHasTaskId id, Status status, Task task, User user) {
		this.id = id;
		this.status = status;
		this.task = task;
		this.user = user;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userIdUser", column = @Column(name = "User_idUser", nullable = false)),
			@AttributeOverride(name = "taskIdTask", column = @Column(name = "Task_idTask", nullable = false)),
			@AttributeOverride(name = "statusIdStatus", column = @Column(name = "Status_idStatus", nullable = false)) })
	public UserHasTaskId getId() {
		return this.id;
	}

	public void setId(UserHasTaskId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Status_idStatus", nullable = false, insertable = false, updatable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Task_idTask", nullable = false, insertable = false, updatable = false)
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_idUser", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
